package com.rightteam.accountbook.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.rightteam.accountbook.bean.WalletBean;
import com.rightteam.accountbook.bean.BillBean;

import com.rightteam.accountbook.greendao.WalletBeanDao;
import com.rightteam.accountbook.greendao.BillBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig walletBeanDaoConfig;
    private final DaoConfig billBeanDaoConfig;

    private final WalletBeanDao walletBeanDao;
    private final BillBeanDao billBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        walletBeanDaoConfig = daoConfigMap.get(WalletBeanDao.class).clone();
        walletBeanDaoConfig.initIdentityScope(type);

        billBeanDaoConfig = daoConfigMap.get(BillBeanDao.class).clone();
        billBeanDaoConfig.initIdentityScope(type);

        walletBeanDao = new WalletBeanDao(walletBeanDaoConfig, this);
        billBeanDao = new BillBeanDao(billBeanDaoConfig, this);

        registerDao(WalletBean.class, walletBeanDao);
        registerDao(BillBean.class, billBeanDao);
    }
    
    public void clear() {
        walletBeanDaoConfig.clearIdentityScope();
        billBeanDaoConfig.clearIdentityScope();
    }

    public WalletBeanDao getWalletBeanDao() {
        return walletBeanDao;
    }

    public BillBeanDao getBillBeanDao() {
        return billBeanDao;
    }

}
